
DROP TABLE country IF EXISTS;

CREATE TABLE country(
	COUNTRY_ID INTEGER NOT NULL AUTO_INCREMENT,
	COUNTRY_NAME VARCHAR(50) NOT NULL,
    	INDEPENDENT VARCHAR(50) DEFAULT 'false',
	PRIMARY KEY  (COUNTRY_ID)
);




